=== randovania/open-prime-rando/src/open_prime_rando/echoes/legacy_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "$schema": {
            "type": "string",
            "format": "uri"
        },
        "legacy_compatibility": {
            "type": "boolean",
            "default": false,
            "description": "Operate assuming that Claris' Randomizer was already used in the input files"
        },
        "worlds": {
            "type": "object",
            "properties": {
                "Great Temple": { "$ref": "#/$defs/world" },
                "Temple Grounds": { "$ref": "#/$defs/world" },
                "Agon Wastes": { "$ref": "#/$defs/world" },
                "Torvus Bog": { "$ref": "#/$defs/world" },
                "Sanctuary Fortress": { "$ref": "#/$defs/world" }
            },
            "default": {},
            "additionalProperties": false,
            "$comment": "The list of properties is replaced in runtime with all worlds in the provided ISO."
        },
        "small_randomizations": {
            "properties": {
                "seed": {
                    "type": "number",
                    "description": "Number to use as seed for the small randomizations"
                },
                "echo_locks": {
                    "type": "boolean",
                    "description": "Randomize the solution of the Annihilator+Echo Visor puzzles sound puzzles.",
                    "default": true
                },
                "minigyro_chamber": {
                    "type": "boolean",
                    "description": "Randomize the solution of the puzzle in Minigyro Chamber.",
                    "default": true
                },
                "rubiks": {
                    "type": "boolean",
                    "description": "Randomize the solution of the color puzzles in Main Gyro Chamber.",
                    "default": true
                }
            },
            "additionalProperties": false,
            "required": [
                "seed"
            ]
        },
        "area_patches": {
            "type": "object",
            "properties": {
                "rebalance_world": {
                    "type": "boolean",
                    "description": "Apply patches that rebalance aspects of the game for a better rando experience",
                    "default": true
                }
            },
            "description": "Pre-written patches for specific areas",
            "default": {}
        },
        "inverted": {
            "type": "boolean",
            "description": "Inverts Light and Dark Aether",
            "default": false
        },
        "auto_enabled_elevators": {
            "type": "boolean",
            "description": "Set elevators to be activated on room load",
            "default": false
        },
        "cosmetics": {
            "type": "object",
            "properties": {
                "suits": {
                    "type": "object",
                    "properties": {
                        "varia": {
                            "$ref": "#/$defs/suit_skin"
                        },
                        "dark": {
                            "$ref": "#/$defs/suit_skin"
                        },
                        "light": {
                            "$ref": "#/$defs/suit_skin"
                        }
                    },
                    "additionalProperties": false,
                    "$comment": "Choose from a number of custom suit textures"
                }
            },
            "additionalProperties": false,
            "required": [
                "suits"
            ]
        },
        "tweaks": {
            "type": "object",
            "description": "Allows arbitrary changes to the tweaks",
            "propertyNames": {
                "enum": [
                    "TweakGui",
                    "TweakTargeting",
                    "TweakPlayerRes",
                    "TweakPlayerControls2",
                    "TweakParticle",
                    "TweakGuiColors",
                    "TweakGame",
                    "TweakPlayer2",
                    "TweakSlideShow",
                    "TweakBall",
                    "TweakAutoMapper",
                    "TweakPlayerControls",
                    "TweakPlayerGunMuli",
                    "TweakPlayerGun",
                    "TweakCameraBob",
                    "TweakPlayer"
                ]
            },
            "additionalProperties": {
                "type": "object",
                "description": "Mapping of full property path to new value. For nested properties, include parent property names split with .",
                "additionalProperties": true
            },
            "examples": [
                {
                    "TweakPlayer": {
                        "collision.ball_radius": 0.5,
                        "dark_world.damage_per_second.di_damage": 1,
                        "dark_world.unknown_0x19275a97": 0.5
                    }
                }
            ]
        }
    },
    "required": [
        "small_randomizations",
        "cosmetics"
    ],
    "additionalProperties": false,
    "$defs": {
        "world": {
            "type": "object",
            "properties": {
                "areas": {
                    "type": "object",
                    "patternProperties": {
                        ".*": {
                            "$ref": "#/$defs/area"
                        }
                    }
                }
            },
            "required": ["areas"],
            "additionalProperties": false,
            "$comment": "The list of areas is replaced in runtime with the existing areas of each specific world."
        },
        "area": {
            "type": "object",
            "properties": {
                "docks": {
                    "type": "object",
                    "patternProperties": {
                        ".*": {
                            "$ref": "#/$defs/dock"
                        }
                    },
                    "default": {},
                    "$comment": "The list of docks is replaced in runtime with the existing docks of each specific area."
                },
                "layers": {
                    "type": "object",
                    "patternProperties": {
                        ".*": {
                            "type": "boolean"
                        }
                    },
                    "default": {},
                    "description": "Change the default state of this area's layers.",
                    "$comment": "The list of layers is replaced in runtime with the existing layers of each specific area."
                },
                "low_memory_mode": {
                    "type": "boolean",
                    "default": false,
                    "description": "Some areas are riding the memory/object limit. Certain patches will account for these limitations if this flag is set."
                },
                "new_name": {
                    "type": ["string", "null"],
                    "default": null,
                    "description": "If set, rename the area to this value"
                },
                "elevators": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "instance_id": {
                                "type": "integer",
                                "description": "The instance id of the WorldTeleporter object to be updated."
                            },
                            "target_assets": {
                                "$ref": "#/$defs/area_identifier",
                                "description": ""
                            },
                            "target_strg": {
                                "type": ["integer", "null"],
                                "default": null,
                                "description": "The STRG of the Scan that unlocks the elevator. If set, it's updated with `target_name`."
                            },
                            "target_name": {
                                "type": "string",
                                "description": "The name of the destination of this connects to. Used by `target_strg`."
                            }
                        },
                        "required": [
                            "instance_id",
                            "target_assets",
                            "target_name"
                        ],
                        "additionalProperties": false
                    },
                    "default": [],
                    "description": "Change where WorldTeleporters in this Area connect to"
                }
            },
            "additionalProperties": false
        },
        "dock": {
            "type": "object",
            "properties": {
                "connect_to": {
                    "type": "object",
                    "properties": {
                        "area": {
                            "type": "string"
                        },
                        "dock": {
                            "type": "string"
                        }
                    },
                    "required": ["area", "dock"],
                    "additionalProperties": false
                },
                "old_door_type": {
                    "$ref": "#/$defs/dock_type"
                },
                "new_door_type": {
                    "$ref": "#/$defs/dock_type"
                }
            },
            "default": {},
            "additionalProperties": false
        },
        "dock_type": {
            "type": "string",
            "enum": [
                "Normal",
                "Dark",
                "Light",
                "Annihilator",
                "Disabled",
                "Missile",
                "SuperMissile",
                "PowerBomb",
                "SeekerMissile",
                "ScrewAttack",
                "Bomb",
                "Boost",
                "Grapple",
                "Darkburst",
                "Sunburst",
                "SonicBoom",
                "AgonEnergy",
                "TorvusEnergy",
                "SanctuaryEnergy",
                "DarkVisor",
                "EchoVisor",
                "Cannon",
                "Charge",
                "Power"
            ]
        },
        "area_identifier": {
            "type": "object",
            "properties": {
                "world_asset_id": {
                    "type": "integer",
                    "description": "Asset ID of a MLVL"
                },
                "area_asset_id": {
                    "type": "integer",
                    "description": "Asset ID of a MREA"
                }
            }
        },
        "suit_skin": {
            "type": "string",
            "enum": [
                "player1",
                "player2",
                "player3",
                "player4"
            ],
            "default": "player1"
        }
    }
}

=== randovania/open-prime-rando/tests/test_files/echoes/door_lock.json
{
    "worlds": {
        "Temple Grounds": {
            "areas": {
                "Dynamo Chamber": {
                    "elevators": [],
                    "docks": {
                        "North": {
                            "old_door_type": "Normal",
                            "new_door_type": "PowerBomb"
                        }
                    },
                    "layers": {
                        "1st Pass Scripting": false,
                        "2nd Pass Scripting": true
                    },
                    "low_memory_mode": false
                },
                "Trooper Security Station": {
                    "elevators": [],
                    "docks": {},
                    "layers": {
                        "1st Pass": false,
                        "2nd Pass": true
                    }
                },
                "Landing Site": {
                    "elevators": [],
                    "docks": {
                        "North": {
                            "old_door_type": "Normal",
                            "new_door_type": "SeekerMissile"
                        }
                    },
                    "layers": {},
                    "low_memory_mode": false
                },
                "Service Access": {
                    "elevators": [],
                    "docks": {
                        "South": {
                            "old_door_type": "Normal",
                            "new_door_type": "SeekerMissile"
                        },
                        "East": {
                            "old_door_type": "Normal",
                            "new_door_type": "Dark"
                        },
                        "West": {
                            "old_door_type": "SuperMissile",
                            "new_door_type": "PowerBomb"
                        }
                    },
                    "layers": {},
                    "low_memory_mode": false
                },
                "Path of Honor": {
                    "elevators": [],
                    "docks": {
                        "West": {
                            "old_door_type": "Normal",
                            "new_door_type": "Dark"
                        },
                        "North": {
                            "old_door_type": "SeekerMissile",
                            "new_door_type": "Normal"
                        }
                    },
                    "layers": {},
                    "low_memory_mode": false
                },
                "Meeting Grounds": {
                    "elevators": [],
                    "docks": {
                        "North": {
                            "old_door_type": "Normal",
                            "new_door_type": "SeekerMissile"
                        },
                        "EastBottom": {
                            "old_door_type": "SuperMissile",
                            "new_door_type": "PowerBomb"
                        }
                    },
                    "layers": {},
                    "low_memory_mode": false
                },
                "Hive Transport Area": {
                    "elevators": [],
                    "docks": {
                        "group35_blue_01_Temple_Hive_1_4_East_BigDoor": {
                            "old_door_type": "Normal",
                            "new_door_type": "PowerBomb"
                        }
                    },
                    "layers": {},
                    "low_memory_mode": false
                },
                "Hall of Honored Dead": {
                    "elevators": [],
                    "docks": {
                        "South": {
                            "old_door_type": "SeekerMissile",
                            "new_door_type": "Normal"
                        }
                    },
                    "layers": {},
                    "low_memory_mode": false
                },
                "Hall of Eyes": {
                    "elevators": [],
                    "docks": {
                        "West": {
                            "old_door_type": "SuperMissile",
                            "new_door_type": "Normal"
                        },
                        "South": {
                            "old_door_type": "Normal",
                            "new_door_type": "SeekerMissile"
                        }
                    },
                    "layers": {},
                    "low_memory_mode": false
                },
                "Hive Chamber C": {
                    "elevators": [],
                    "docks": {
                        "North1": {
                            "old_door_type": "Normal",
                            "new_door_type": "Normal"
                        },
                        "blue_01_Temple_Hive_1_4_West_BigDoor": {
                            "old_door_type": "Normal",
                            "new_door_type": "PowerBomb"
                        }
                    },
                    "layers": {},
                    "low_memory_mode": false
                },
                "Hive Tunnel": {
                    "elevators": [],
                    "docks": {
                        "East1": {
                            "old_door_type": "Normal",
                            "new_door_type": "PowerBomb"
                        }
                    },
                    "layers": {},
                    "low_memory_mode": false
                },
                "Base Access": {
                    "elevators": [],
                    "docks": {
                        "South": {
                            "old_door_type": "SuperMissile",
                            "new_door_type": "Normal"
                        }
                    },
                    "layers": {},
                    "low_memory_mode": false
                },
                "Path of Eyes": {
                    "elevators": [],
                    "docks": {
                        "North": {
                            "old_door_type": "SuperMissile",
                            "new_door_type": "PowerBomb"
                        },
                        "East": {
                            "old_door_type": "SuperMissile",
                            "new_door_type": "Normal"
                        }
                    },
                    "layers": {},
                    "low_memory_mode": false
                },
                "Hive Chamber B": {
                    "elevators": [],
                    "docks": {
                        "South": {
                            "old_door_type": "Normal",
                            "new_door_type": "Missile"
                        }
                    },
                    "layers": {},
                    "low_memory_mode": false
                },
                "Hive Save Station": {
                    "elevators": [],
                    "docks": {
                        "South": {
                            "old_door_type": "Normal",
                            "new_door_type": "Normal"
                        }
                    },
                    "layers": {},
                    "low_memory_mode": false
                },
                "Command Chamber": {
                    "elevators": [],
                    "docks": {
                        "East": {
                            "old_door_type": "Normal",
                            "new_door_type": "PowerBomb"
                        },
                        "West2": {
                            "old_door_type": "Normal",
                            "new_door_type": "PowerBomb"
                        }
                    },
                    "layers": {},
                    "low_memory_mode": false
                },
                "War Ritual Grounds": {
                    "elevators": [],
                    "docks": {
                        "EastBottom": {
                            "old_door_type": "Normal",
                            "new_door_type": "SeekerMissile"
                        },
                        "North": {
                            "old_door_type": "SuperMissile",
                            "new_door_type": "Normal"
                        }
                    },
                    "layers": {},
                    "low_memory_mode": false
                },
                "Windchamber Gateway": {
                    "elevators": [],
                    "docks": {
                        "South": {
                            "old_door_type": "SuperMissile",
                            "new_door_type": "PowerBomb"
                        },
                        "East": {
                            "old_door_type": "PowerBomb",
                            "new_door_type": "Missile"
                        }
                    },
                    "layers": {},
                    "low_memory_mode": false
                },
                "Torvus Transport Access": {
                    "elevators": [],
                    "docks": {
                        "South": {
                            "old_door_type": "Missile",
                            "new_door_type": "Sunburst"
                        }
                    },
                    "layers": {},
                    "low_memory_mode": false
                },
                "Temple Assembly Site": {
                    "elevators": [],
                    "docks": {
                        "South1": {
                            "old_door_type": "Missile",
                            "new_door_type": "PowerBomb"
                        },
                        "West": {
                            "old_door_type": "Normal",
                            "new_door_type": "Missile"
                        }
                    },
